import type {
  DestinationCatalogItem,
} from "@/components/destination/catalog/types";

export const destinationCatalogItems: DestinationCatalogItem[] = [
  {
    id: "jp",
    name: "Nhật Bản",
    countryCode: "JP",
    continentLabel: "Châu Á",
    durationLabel: "1 – 30 ngày",
    dataLabel: "1GB – Không giới hạn",
    priceFrom: 69000,
    currency: "VND",
    href: "/destinations/japan",
  },
  {
    id: "kr",
    name: "Hàn Quốc",
    countryCode: "KR",
    continentLabel: "Châu Á",
    durationLabel: "1 – 30 ngày",
    dataLabel: "1GB – Không giới hạn",
    priceFrom: 69000,
    currency: "VND",
    href: "/destinations/south-korea",
  },
  {
    id: "sg",
    name: "Singapore",
    countryCode: "SG",
    continentLabel: "Châu Á",
    durationLabel: "1 – 30 ngày",
    dataLabel: "500MB – Không giới hạn",
    priceFrom: 49000,
    currency: "VND",
    href: "/destinations/singapore",
  },
  {
    id: "th",
    name: "Thái Lan",
    countryCode: "TH",
    continentLabel: "Châu Á",
    durationLabel: "1 – 30 ngày",
    dataLabel: "1GB – Không giới hạn",
    priceFrom: 59000,
    currency: "VND",
    href: "/destinations/thailand",
  },
  {
    id: "us",
    name: "Hoa Kỳ",
    countryCode: "US",
    continentLabel: "Bắc Mỹ",
    durationLabel: "1 – 30 ngày",
    dataLabel: "1GB – Không giới hạn",
    priceFrom: 159000,
    currency: "VND",
    href: "/destinations/united-states",
  },
  {
    id: "fr",
    name: "Pháp",
    countryCode: "FR",
    continentLabel: "Châu Âu",
    durationLabel: "1 – 30 ngày",
    dataLabel: "1GB – Không giới hạn",
    priceFrom: 119000,
    currency: "VND",
    href: "/destinations/france",
  },
];