import type {
  PopularDestination,
} from "@/components/destination/types";

export const popularDestinations: PopularDestination[] = [
  {
    id: "japan",
    name: "Nhật Bản",
    slug: "japan",
    href: "/destinations/japan",
    countryCode: "JP",
    continent: "asia",
    imageSrc: "/images/destinations/japan.jpg",
    imageAlt:
      "Núi Phú Sĩ và ngôi chùa truyền thống tại Nhật Bản",
    badge: "Phổ biến",
    durationLabel: "1 – 30 ngày",
    priceFrom: 69000,
    currency: "VND",
    networkLabel: "Docomo • SoftBank",
    popular: true,
  },
  {
    id: "south-korea",
    name: "Hàn Quốc",
    slug: "south-korea",
    href: "/destinations/south-korea",
    countryCode: "KR",
    continent: "asia",
    imageSrc: "/images/destinations/korea.jpg",
    imageAlt:
      "Thành phố Seoul nhìn từ tháp Namsan tại Hàn Quốc",
    badge: "Phổ biến",
    durationLabel: "1 – 30 ngày",
    priceFrom: 69000,
    currency: "VND",
    networkLabel: "SK Telecom • KT",
    popular: true,
  },
  {
    id: "thailand",
    name: "Thái Lan",
    slug: "thailand",
    href: "/destinations/thailand",
    countryCode: "TH",
    continent: "asia",
    imageSrc: "/images/destinations/thailand.jpg",
    imageAlt:
      "Cung điện và chùa tại Bangkok, Thái Lan",
    durationLabel: "1 – 30 ngày",
    priceFrom: 59000,
    currency: "VND",
    networkLabel: "AIS • TrueMove H",
    popular: true,
  },
  {
    id: "singapore",
    name: "Singapore",
    slug: "singapore",
    href: "/destinations/singapore",
    countryCode: "SG",
    continent: "asia",
    imageSrc: "/images/destinations/singapore.jpg",
    imageAlt:
      "Marina Bay Sands và Merlion tại Singapore",
    durationLabel: "1 – 30 ngày",
    priceFrom: 49000,
    currency: "VND",
    networkLabel: "Singtel • StarHub",
    popular: true,
  },
  {
    id: "united-states",
    name: "Hoa Kỳ",
    slug: "united-states",
    href: "/destinations/united-states",
    countryCode: "US",
    continent: "north-america",
    imageSrc: "/images/destinations/usa.jpg",
    imageAlt:
      "Tượng Nữ thần Tự do và đường chân trời New York, Hoa Kỳ",
    durationLabel: "1 – 30 ngày",
    priceFrom: 159000,
    currency: "VND",
    networkLabel: "T-Mobile • AT&T",
    popular: true,
  },
  {
    id: "global",
    name: "Toàn cầu",
    slug: "global",
    href: "/esim?category=global",
    continent: "all",
    imageSrc: "/images/destinations/global.jpg",
    imageAlt:
      "Hình minh họa kết nối internet toàn cầu",
    durationLabel: "1 – 90 ngày",
    priceFrom: 299000,
    currency: "VND",
    networkLabel: "200+ quốc gia",
    popular: true,
  },
];